### ISSUE TITLE
Issues trying to lunch the stack

### ISSUE THREAD

**Issue by portacha** [aws-samples/aws-refarch-moodle#11]
Sorry for this question but how can i lunch this stack. I try it but i get the same error all time.

rds | CREATE_FAILED | Embedded stack arn:aws:cloudformation:us-east-1:########:stack/moodlecftest2-rds-#############-###-###-############## was not successfully created: The following resource(s) failed to create: [DatabaseCluster].
-- | -- | -- | --

**Comment by brianjbeach** [comment]
This should be fixed by last merge
