### ISSUE TITLE
i wanna use moodle 3.8 with this architecture

### ISSUE THREAD

**Issue by vvrtsaix** [aws-samples/aws-refarch-moodle#13]
i changed 04-web.yaml file:
- php version 7.0 => 7.2
- php packages php70-intl => php72-intl
- postgrey 93 => 10
- https://download.moodle.org/stable34/moodle-3.4.tgz  => https://download.moodle.org/stable38/moodle-3.8.tgz
but it isnt work can you help

**Comment by Darkhaamn** [comment]
Me too please help us

**Comment by jtrollin** [comment]
Please pull latest as this upgrades moodle to 3.8 and PHP 7.3
