### ISSUE TITLE
Database instance size options

### ISSUE THREAD

**Issue by jldinh** [aws-samples/aws-refarch-moodle#2]
Hi,
I noticed database options start at db.r4.large. Is there any reason why smaller options were not included, or could I edit the template to add more options?

**Comment by brianjbeach** [comment]
The options in the template were the ones available when the template was created. AWS is always adding new options. You can simply update the template. If you do, please submit a pull request.

**Comment by dgomesbr** [comment]
Hey @brianjbeach, I've just pushed the necessary updates.

**Comment by jldinh** [comment]
Hi @dgomesbr, thanks for doing the work, but I was wondering whether the smaller DB sizes I mentioned in the original ticket are actually valid options: I initially thought the DB was a plain PostgreSQL RDS, but it seems it is actually a PostgreSQL-compatible Aurora DB, and I have not found any mentions of smaller instance sizes for Aurora on the AWS website.
