### ISSUE TITLE
Allowed instances update for Cape-Town af-south-1 region

### ISSUE THREAD

**Issue by Jaco-Louis** [aws-samples/aws-refarch-moodle#25]
Good day

Several of the instance types used in the reference architecture aren't available in the Cape-Town af-south-1 region. An example is the db.r4.large instance for the RDS. Could this perhaps be updated to enable deployment to the Cape-Town region?

Kind regards
Jaco-Louis

**Comment by rlorenzo** [comment]
@Jaco-Louis You can change the template files to replace references of db.r4.large to db.r5.large. That's what we did here: https://github.com/ucla/aws-refarch-moodle/commit/96da23d7b2d6b9dfc7f6cbcbdd7831af0d1ab621

**Comment by vrioux** [comment]
Hi, there is a new revision of this reference architecture that was just merged. Please let us know if there is any issue with it. Closing this as it is quite old. Please reopen if still up-to-date. Thanks!
