### ISSUE TITLE
Limitation DB Connections 

### ISSUE THREAD

**Issue by ghost** [aws-samples/aws-refarch-moodle#26]
Hi, there is some DB connection limit on Moodle? 

![image](https://user-images.githubusercontent.com/47001201/95253289-90f01580-07f4-11eb-86d8-f520ee710533.png)

We have installed from this stack, and everything is working fine, but sometimes when we have a lot of users, the Database cluster fails. 

Database is Cluster Aurora PostgreSQL db.r4.2xlarge, CPU and Memory usage is not high and we receive 
Error: Database connection failed.
It is possible that the database is overloaded or otherwise not running properly.

Any idea where to see? Logs in DB only says could not receive data from client: Connection reset by peer, but no more info

**Comment by rikimontano** [comment]
Did you found any solution to the database connection failed problem? @gcaride

**Comment by gcaride** [comment]
> Did you found any solution to the database connection failed problem? @gcaride

Hi @rikimontano, unfortunately no!

Are you having the same problem? Do you have any type of workaround?

**Comment by flaviobarros** [comment]
Just out of curiosity, what are the costs of a stack like that?

**Comment by vrioux** [comment]
Hi, closing as this is a quite old issue. Please reopen if the issue persists. Thanks!
