### ISSUE TITLE
Stack stuck on  REVIEW_IN_PROGRESS	

### ISSUE THREAD

**Issue by collisiondetection** [aws-samples/aws-refarch-moodle#30]
The template   creation process seems  to be  stuck  on  REVIEW_IN_PROGRESS

![image](https://user-images.githubusercontent.com/4151385/126392344-2315f319-bc9a-4814-9ee2-3eb14ef08d50.png)

Do I need to tweak something?

**Comment by vrioux** [comment]
Hi, closing as this is a quite old issue. If still valid, please reopen. Thanks!
