### ISSUE TITLE
Change in version aurora-postgresql

### ISSUE THREAD

**Issue by gustaffvho** [aws-samples/aws-refarch-moodle#35]
Change in version aurora-postgresql 03-rds.yaml

 DatabaseInstanceType:
    AllowedValues:
      - db.r4.large ##version aurora-postgresql13 no accept r4
      - db.r4.xlarge
      - db.r4.2xlarge
      - db.r4.4xlarge
      - db.r4.8xlarge
      - db.r4.16xlarge
      - db.r5.large ## version aurora-postgresql12 accept r5
      - db.r5.xlarge
      - db.r5.2xlarge
      - db.r5.4xlarge
      - db.r5.8xlarge
      - db.r5.16xlarge

   DBClusterParameterGroupName: default.aurora-postgresql13 ##Change version aurora-postgresql to from 12 to 13

**Comment by vrioux** [comment]
This is now fixed with the revision 2 that was just merged.
