### ISSUE TITLE
Invalid config.php (error 500)

### ISSUE THREAD

**Issue by jldinh** [aws-samples/aws-refarch-moodle#4]
The file generated at `/var/www/moodle/html/config.php` does not parse as PHP, because the `templates/04-web.yaml` file of this repo uses backtick quotes.

When `/var/www/moodle/html/config.php` is generated, the backticks are substituted by question marks, leading to a parsing error and an error 500 when accessing the website.

This bug was introduced in #1.

**Comment by brianjbeach** [comment]
So those were not backtics. They look like the quotes that MS word adds. Anyway I fixed them.
