### ISSUE TITLE
failed to create: [NatEIP0, NatEIP1]

### ISSUE THREAD

**Issue by kurt-plaza** [aws-samples/aws-refarch-moodle#42]
When creating the stack, I get the following error:
Embedded stack arn:aws:cloudformation:us-east-2:004749571273:stack/MoodleLink2-vpc-4WE3TZH1DORN/3ff97630-c822-11ed-bc0e-02905d19378a was not successfully created: The following resource(s) failed to create: [NatEIP0, NatEIP1].

**Comment by anmalatesta** [comment]
Hi,
Perhaps the number of EIPs has reached the limit of 5 for your region and it is not possible to create more EIPs.

**Comment by kurt-plaza** [comment]
That's right, it was my mistake
