### ISSUE TITLE
Cron not running?

### ISSUE THREAD

**Issue by mattrxcool** [aws-samples/aws-refarch-moodle#43]
Hi I deployed this stack a couple days ago however I don't understand how it handles the Cron jobs for Moodle.

Under site admin > reports I am seeing the following critical error:
"The admin/cli/cron.php script has never been run and should run every 1 min"

**Comment by mattrxcool** [comment]
An update. I Connected to the EC2 instance running the Moodle code and did sudo vim /etc/crontab and added a line for
* * * * * root /usr/bin/php /var/www/moodle/html/admin/cli/cron.php
and now the scheduled tasks are running and the Cron error has gone away. But is this the correct way to do this? And does it need to be done on every instance?

**Comment by vrioux** [comment]
We will look into this. Thanks for the issue. By the way, the Moodle documentation states that we can run the cron job on multiple servers without issue as it uses task locking to prevent the same task from running on different servers. See here: https://docs.moodle.org/402/en/Cron

**Comment by vrioux** [comment]
Fixed on latest merge. Thanks for reporting!
