### ISSUE TITLE
Older Moodle version in template

### ISSUE THREAD

**Issue by jchavezb-37** [aws-samples/aws-refarch-moodle#48]
actually Moddle has 4.2+ version but the template has Moddle 4.1 version.  What must I change in files to install the latest Moddle version?

**Comment by vrioux** [comment]
Hi, you can see where the Moodle version is downloaded here: 
https://github.com/aws-samples/aws-refarch-moodle/blob/8f03b6b0116de42b23770b81dc52f72a3624e371/templates/03-pipelinehelper.yaml#L536

You can thus replace that URL with https://download.moodle.org/download.php/direct/stable402/moodle-latest-402.tgz to get Moodle 4.2.2+ 

We will also update this as soon as possible. Thanks for reporting it!

**Comment by vrioux** [comment]
The [new release](https://github.com/aws-samples/aws-refarch-moodle/releases/tag/release-2.0.1-moodle-422) has the updated URL for Moodle 4.2.2+
