### ISSUE TITLE
Release Change

### ISSUE THREAD

**Issue by kokowas** [aws-samples/aws-refarch-moodle#52]
hi vrioux
when the deployment is completed , release change give me error & i got this email
The launch template associated with this Auto Scaling group cannot be found. Each time a scale out operation is performed, it will be prevented until you make a change that fixes the issue.
thank you in advance

**Comment by vrioux** [comment]
Hi, thanks for opening this issue! The error seems to indicate a Launch Template was removed. You could create a new one and apply it to the Auto Scaling Group, however that may break your pipeline. Please let me know if the issue persists. Thanks!

**Comment by vrioux** [comment]
Hi @kokowas, this has now been fixed! Thanks!
