### ISSUE TITLE
Error in after_install.sh pipeline

### ISSUE THREAD

**Issue by albertolarah** [aws-samples/aws-refarch-moodle#54]
can't read /var/www/moodle/html/cache/stores/memcached/lib.php

**Comment by albertolarah** [comment]
After install Moodle, change the IsMoodleSetupCompleted to Yes and run the pipeline the script "after_install.sh" failed with the following error:

<img width="883" alt="Captura de pantalla 2024-01-25 a las 10 55 13" src="https://github.com/aws-samples/aws-refarch-moodle/assets/1539802/9010bc58-801f-4cee-b052-4806068476db">

**Comment by vrioux** [comment]
Hi, thanks for reporting this issue! We will look at it as soon as possible. Please hold on. Thanks!

**Comment by vrioux** [comment]
Hi @albertolarah, this has now been fixed. Thanks!
