### ISSUE TITLE
Existing Moodle setup migrate to this architecture

### ISSUE THREAD

**Issue by anuprathod774** [aws-samples/aws-refarch-moodle#57]
Hi, We have an existing Moodle setup which is customized as per our requirements. We do have a GitHub repository.

How can we migrate that to this architecture?

Please help.

**Comment by vrioux** [comment]
Hi, thanks for reaching out! Are you able to share your GitHub repository? Have you reached out to your AWS Solutions Architect? If not, please reach out to vrioux@amazon.com, and I will be happy to help you find the proper people to help you!

**Comment by vrioux** [comment]
Closing as we will help privately.
