### ISSUE TITLE
AWS EFS is very slow for administration in moodle

### ISSUE THREAD

**Issue by devops-robotiq** [aws-samples/aws-refarch-moodle#7]
Hi ,

AWS EFS for the administration side in moodle are very slow ..... do you have a workaround for this ?

Thanks a lot

**Comment by devops-robotiq** [comment]
Is now done !

**Comment by surajitkundu29** [comment]
@devops-robotiq I am also facing the same issue, Can you please let me know what you did ?

**Comment by devops-robotiq** [comment]
Hi,

We have just activate the caching and after, everything is okay !
